config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root  "home#index"
  get "store", to: "store#index"  , as: :store
  get "product", to: "product#index"
  get "sign_up", to: "registration#new"
  post "sign_up" ,  to: "registration#create"
  
  get "password" , to: "passwords#edit", as: :edit_password
  patch "password" , to: "passwords#update"
     
  get "password/reset" , to: "password_resets#new"
  post "password/reset" , to: "password_resets#create"
  get "password/reset/edit" , to: "password_resets#edit"
  patch "password/reset/edit" , to: "password_resets#update"
     
  delete "logout" ,  to: "sessions#destroy"
  get "log_in", to: "sessions#new" 
  post "log_in" ,  to: "sessions#create" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email , presence: true , format: { with: /\w+([\.-]?\w+)*@\w+([\.-]?\w+)/, message: " must be a vaild email address" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

   def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
       end
    end


    def require_user_logged_in!
        redirect_to log_in_path  , alert: "you have to sign in first" if Current.user.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
       if session[:user_id]
            @user = User.find(session[:user_id])
       end
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end
end   

app/controllers/main_controller.rb
class MainController < ActionController
    def index
    end 
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

    def new
    end

    def create 
        @user = User.find_by(email:params[:email])

        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path , notice: "if your account was found , we have sent reet email to your email box !"
    end

    def edit 
        @user = User.find_signed(params[:token])
    end

    def update 
        @user = User.find_signed(params[:token])
        if @user.update(password_params)
            redirect_to log_in_path , notice: "your password updated successfuly!"
        else
            render :edit
        end 
    end

    private

    def  password_params 
        params.require(:user).permit(:password , :password_confirmation)
    end


end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

    before_action :require_user_logged_in!


    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path , notice: "password updated"
            else
                render :edit
            end
    end

    private 

    def password_params
        params.require(:user).permit(:password , :password_confirmation)
    end
end
 

app/controllers/product_controller.rb
class ProductController < ApplicationController
    def index
        
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to root_path , notice: "Successfuly created account!"
        else
            render :new 
        end    
    end    

    def user_params
        #security upcoming
        params.require(:user).permit(:email, :password, :password_confirmation , :name)
    end   
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil 
        redirect_to root_path , notice: "you are logged out"
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in"

        else
            flash.now[:alert] = "Invaild Email or Password"
            render :new 
        end
    end
    def new
        
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
    def index
        if session[:user_id]
            @user = User.find(session[:user_id])
       end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "bootstrap.min" %>
    
   <script src="https://unpkg.com/jquery@3.7.0/dist/jquery.js" ></script>
   <script src="https://unpkg.com/bootstrap@4.5.0/dist/js/bootstrap.min.js" ></script>
  </head>

  <body>
    <%= render partial:"shared/navbar"%>
    <div class="container">
    <%= render partial:"shared/flash"%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Create New Password</h1>

<%= form_with model: @user , url: password_reset_edit_path(token: params[:token]) do |form|%>

    <div class="form-group mb-3">
        <label for="exampleInputEmail1">New Password</label>
        <%= form.password_field :password , class:"form-control" , placeholder: "test@123"%>
    </div>
    <div class="form-group mb-3">
        <label for="exampleInputEmail1">New Password Confirmation</label>
        <%= form.password_field :password_confirmation , class:"form-control" %>
    </div>

   <%if @user.errors.any? %>
    <div class="alert alert-danger mt-3">
        <% @user.errors.full_messages.each  do |msg|%>
            <li>
            <%= msg%>
            </li>
        <%end%>
        </div>
    <%end%>
    
    <%= form.submit "Update" , class:"btn btn-primary" %> 

<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_with url: password_reset_path do |form|%>

 <div class="form-group mb-3">
        <label for="exampleInputEmail1">Email address</label>
        <%= form.text_field :email , class:"form-control" , placeholder: "user@test.com" %>
    </div>
   
    <%= form.submit "Send" , class:"btn btn-primary" %> 

<% end %>

app/views/product/index.html.erb
<h1>product</h1>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
        <%= link_to "Home" , root_path , class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Product" , product_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Store" , store_path , class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <%# <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> %>
      <% if Current.user%>
        <div class="nav-link d-flex nav-item">
          <%= Current.user.name %>&nbsp;&nbsp;
        </div>
        <div class="dropdown  pr-5">
          <button class="btn btn-outline-dark dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Settings
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <span class="dropdown-item" >Hello <%= Current.user.name %>
            </span> 
            <button class="dropdown-item" type="button">action</button>
            <%= button_to "logout" , logout_path , method: :delete , class: "dropdown-item"%>
            <%= link_to "edit password", edit_password_path , class: "dropdown-item"%>
          </div>
        </div>
      <%else%>
        <%= link_to "Sign Up" , sign_up_path , class:"btn btn-primary ml-3"%>&nbsp;
        <%= link_to "Login" , log_in_path , class:"btn btn-outline-primary ml-3"%>&nbsp;
      <% end%>
    </div>
  </div>
</nav>

app/views/store/index.html.erb
<div>
<h1>Store</h1>
   
</div>